name: Build and Upload llama-cpp-python Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version (e.g. v0.3.4-cu121)"
        required: true
      publish_release:
        description: "Upload wheels to GitHub Release"
        required: false
        default: "true"

permissions:
  contents: write

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: aarch64
          - os: macos-latest
            arch: universal2
          - os: windows-latest
            arch: AMD64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system deps (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ unzip patchelf

      - name: Install Python build tools
        run: |
          pip install --upgrade pip
          pip install cibuildwheel build auditwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: "pp* *-musllinux*"
          CIBW_ENVIRONMENT: >
            CMAKE_ARGS="-DLLAMA_NATIVE=OFF -DLLAMA_BLAS=ON -DLLAMA_OPENBLAS=ON"
            CMAKE_BUILD_PARALLEL_LEVEL=2
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Post-process and repair wheels
        run: |
          mkdir -p repaired_wheels
          for whl in wheelhouse/*.whl; do
            echo "Unzipping: $whl"
            dir=$(mktemp -d)
            unzip "$whl" -d "$dir"

            echo "Searching for .so file..."
            so_file=$(find "$dir" -name "*.so" | head -n1)
            echo "Found .so file: $so_file"

            echo "Running ldd to detect missing shared libs..."
            ldd "$so_file" || true

            # Locate vendor folder where ggml-built libs are stored
            VENDOR_GGML_DIR="vendor/llama.cpp/build"
            TARGET_LIB_DIR="$dir/llama_cpp"

            if [ -d "$VENDOR_GGML_DIR" ]; then
              echo "Copying libggml*.so from $VENDOR_GGML_DIR to $TARGET_LIB_DIR..."
              mkdir -p "$TARGET_LIB_DIR"
              cp "$VENDOR_GGML_DIR"/libggml*.so "$TARGET_LIB_DIR"/ || true
            else
              echo "Warning: Vendor directory $VENDOR_GGML_DIR not found!"
            fi

            echo "Listing contents of $TARGET_LIB_DIR"
            ls -lh "$TARGET_LIB_DIR" || true

            echo "Repacking the fixed wheel..."
            repaired_zip="${whl%.whl}-fixed.whl"
            (cd "$dir" && zip -r9 "$OLDPWD/$repaired_zip" .)
            rm -rf "$dir"

            echo "Running auditwheel repair..."
            auditwheel repair "$repaired_zip" -w repaired_wheels || {
              echo "Auditwheel failed on $repaired_zip, skipping..."
            }
          done

      - name: Upload built wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: repaired_wheels/*.whl

  release:
    name: Release to GitHub
    needs: build
    if: ${{ github.event.inputs.publish_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_wheels

      - name: Publish wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: all_wheels/**/*.whl
