name: Build and Publish Wheels

on:
  workflow_dispatch:
    inputs:
      llama_cpp_version:
        description: 'Full llama-cpp-python version (e.g., v0.3.4-cu121)'
        required: true
      publish_release:
        description: "Upload wheels to GitHub Release"
        required: false
        default: "true"

permissions:
  contents: write

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            cibw_arch: auto
            manylinux_image: manylinux2014

          - os: ubuntu-latest
            platform: linux
            arch: aarch64
            cibw_arch: aarch64
            manylinux_image: manylinux2014

          - os: macos-latest
            platform: macos
            arch: universal2
            cibw_arch: universal2

          - os: windows-latest
            platform: windows
            arch: AMD64
            cibw_arch: auto

    steps:
      - name: Set up QEMU (for ARM64)
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Python 3.12.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Checkout llama-cpp-python
        uses: actions/checkout@v4
        with:
          repository: abetlen/llama-cpp-python
          ref: ${{ inputs.llama_cpp_version }}
          submodules: true

      - name: Extract base tag
        id: extract_tag
        shell: bash
        run: |
          TAG="${{ inputs.llama_cpp_version }}"
          BASE_TAG="${TAG%-*}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "base_tag=$BASE_TAG" >> "$GITHUB_OUTPUT"

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential python3-dev libopenblas-dev patchelf

      - name: Install cibuildwheel
        shell: bash
        run: pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        shell: bash
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_ENVIRONMENT: >-
            CMAKE_ARGS="-DLLAMA_CUBLAS=OFF -DLLAMA_METAL=OFF -DLLAMA_OPENBLAS=ON -DLLAMA_NATIVE=OFF -DGGML_BUILD_SHARED=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
          CIBW_SKIP: pp* *musllinux* *-win32
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.manylinux_image }}
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse

      - name: Post-process and repair wheels
        shell: bash
        run: |
          mkdir -p repaired_wheels
          for whl in wheelhouse/*.whl; do
            echo "Unzipping: $whl"
            dir=$(mktemp -d)
            unzip "$whl" -d "$dir"

            echo "Searching for .so file..."
            so_file=$(find "$dir" -name "*.so" | head -n1)
            echo "Found .so file: $so_file"

            echo "Running ldd to detect missing shared libs..."
            ldd "$so_file" || true

            # Locate vendor folder where ggml-built libs are stored
            VENDOR_GGML_DIR="vendor/llama.cpp/build"
            TARGET_LIB_DIR="$dir/llama_cpp"

            if [ -d "$VENDOR_GGML_DIR" ]; then
              echo "Copying libggml*.so from $VENDOR_GGML_DIR to $TARGET_LIB_DIR..."
              mkdir -p "$TARGET_LIB_DIR"
              cp "$VENDOR_GGML_DIR"/libggml*.so "$TARGET_LIB_DIR"/ || true
            else
              echo "Warning: Vendor directory $VENDOR_GGML_DIR not found!"
            fi

            echo "Listing contents of $TARGET_LIB_DIR"
            ls -lh "$TARGET_LIB_DIR" || true

            echo "Repacking the fixed wheel..."
            repaired_zip="${whl%.whl}-fixed.whl"
            (cd "$dir" && zip -r9 "$OLDPWD/$repaired_zip" .)
            rm -rf "$dir"

            echo "Running auditwheel repair..."
            auditwheel repair "$repaired_zip" -w repaired_wheels || {
              echo "Auditwheel failed on $repaired_zip, skipping..."
            }
          done

      - name: Upload built wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: repaired_wheels/*.whl

  release:
    name: Release to GitHub
    needs: build_wheels
    if: ${{ github.event.inputs.publish_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_wheels

      - name: Publish wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: all_wheels/**/*.whl
