name: Build Windows Wheels

on:
  workflow_dispatch:
    inputs:
      llama_cpp_version:
        description: 'Full llama-cpp-python version (e.g., v0.3.4-cu121)'
        required: true

permissions:
  contents: write

jobs:
  build_windows_wheels:
    runs-on: windows-latest
    steps:
      - name: Extract version tag
        id: extract
        run: |
          echo "::set-output name=tag::${{ github.event.inputs.llama_cpp_version }}"
          # Optionally extract base tag here if needed

      - name: Checkout llama-cpp-python
        uses: actions/checkout@v4
        with:
          repository: abetlen/llama-cpp-python
          ref: ${{ github.event.inputs.llama_cpp_version }}
          submodules: true

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: AMD64

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_ARCHS: "AMD64"
          CFLAGS: "/std:c11"
          CXXFLAGS: "/std:c++17 /Zc:__cplusplus"
          CMAKE_ARGS: >-
              -DCMAKE_INSTALL_LIBDIR=llama_cpp
              -DLLAMA_CUBLAS=OFF
              -DLLAMA_METAL=OFF
              -DLLAMA_OPENBLAS=ON
              -DLLAMA_NATIVE=OFF
              -DCMAKE_C_STANDARD=11
              -DCMAKE_CXX_STANDARD=17
              -DCMAKE_C_STANDARD_REQUIRED=ON
              -DCMAKE_CXX_STANDARD_REQUIRED=ON
        run: python -m cibuildwheel --output-dir dist
